services:
  portainer:
    image: portainer/portainer-ce:lts
    command: --admin-password-file=/default-password
    restart: on-failure
    ports:
      - "9000:9000"
    volumes:
      - ./default-password:/default-password
      - ${PORTAINER_DATA_LOCATION}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro    # Mount host Docker socket
